var cards = [
{name:"Red 1", color:"Red", number:1},
{name:"Green 3", color:"Green", number:3},
{name:"Green Draw 2", color:"Green", specialty:"Draw 2"},
{name:"Green 9", color:"Green", number:9},
{name:"Green 1", color:"Green", number:1},
{name:"Green Draw 2", color:"Green", specialty:"Draw 2"},
{name:"Green Skip", color:"Green", specialty:"Skip"},
{name:"Green 2", color:"Green", number:2},
{name:"Green Skip", specialty:"Skip"},
{name:"Green 1", color:"Green", number:1},
{name:"Green Reverse", color:"Green", specialty:"Reverse"},
{name:"Green 4", color:"Green", number:4},
{name:"Red 1", color:"Red", number:1},
{name:"Green 9", color:"Green", number:9},
{name:"Green Draw 2", color:"Green", specialty:"Draw 2"},
{name:"Green 3", color:"Green", number:3},
{name:"Green 1", color:"Green", number:1},
{name:"Green Reverse", color:"Green", specialty:"Reverse"},
{name:"Red 2", color:"Red", number:2},
{name:"Green 7", color:"Green", number:7},
{name:"Green 4", color:"Green", number:4},
{name:"Green Skip", color:"Green", specialty:"Skip"},
{name:"Red 2", color:"Red", number:2},
{name:"Green 5", color:"Green", number:5},
{name:"Green 3", color:"Green", number:3},
{name:"Red 2", color:"Red", number:2},
{name:"Green 6", color:"Green", number:6},
{name:"Green 4", color:"Green", number:4},
{name:"Green Draw 2", color:"Green", specialty:"Draw 2"},
{name:"Red 2", color:"Red", number:2},
{name:"Red 1", color:"Red", number:1},
{name:"Green Draw 2", color:"Green", specialty:"Draw 2"},
{name:"Green 2", color:"Green", number:2},
{name:"Green 7", color:"Green", number:7},
{name:"Green 5", color:"Green", number:5},
{name:"Green 2", color:"Green", number:2},
{name:"Green 6", color:"Green", number:6},
{name:"Green 5", color:"Green", number:5},
{name:"Green 3", color:"Green" number:3},
{name:"Green 4", color:"Green" number:4},
{name:"Green Draw 2", color:"Green", specialty:"Draw 2"},
{name:"Red 1", color:"Red", number:1},
{name:"Green Draw 2", number:"Green", specialty:"Draw 2"},
{name:"Red 1", color:"Red", number:1},
{name:"Green 1", color:"Green", number:1},
{name:"Green Reverse", color:"Green" specialty:"Reverse"},
{name:"Red 2", color:"Red", number:2},
{name:"Green Draw 2", color:"Green", specialty:"Draw 2"},
{name:"Green 6", color:"Green", number:6},
{name:"Red 2", color:"Red", number:2},
{name:"Green 8", color:"Green", number:8},
{name:"Green Draw 2", color:"Green", specialty:"Draw 2"},
{name:"Green 2", color:"Green", number:2},
{name:"Green 8", color:"Green", number:8},
{name:"Green 9", color:"Green", number:9},
{name:"Green 8", color:"Green", number:8},
{name:"Green Draw 2", color:"Green", specialty:"Draw 2"},
{name:"Green 7", color:"Green", number:7},
{name:"Green Draw 2", color:"Green", specialty:"Draw 2"},
{name:"Green 5", color:"Green", number:5},
{name:"Green 7", color:"Green", number:7},
{name:"Green 9", color:"Green", number:9},
{name:"Green Draw 2", color:"Green", specialty:"Draw 2"}];
