var cards = [
{name:"Green 3", color:"Green", number:3},
{name:"Green 9", color:"Green", number:9},
{name:"Green 1", color:"Green", number:1},
{name:"Green 2", color:"Green", number:2},
{name:"Green Skip"},
{name:"Green 1"},
{name:"Green 4"},
{name:"Red 1"},
{name:"Red 2"},
{name:"Green 3"},
{name:"Green 1"},
{name:"Red 2"},
{name:"Green 4"},
{name:"Red 1"},
{name:"Red 2"},
{name:"Green 5"},
{name:"Green 3"},
{name:"Red 2"},
{name:"Green 4"},
{name:"Red 1"},
{name:"Green 2"},
{name:"Green 7"},
{name:"Green 5"},
{name:"Green 2"},
{name:"Green 6"},
{name:"Green 5"},
{name:"Green 3"},
{name:"Green 4"},
{name:"Red 1"},
{name:"Green Draw 2"},
{name:"Red 1"},
{name:"Green 1"},
{name:"Red 2"},
{name:"Green 6"},
{name:"Green 7"},
{name:"Green 6"},
{name:"Green Reverse"},
{name:"Red 2"},
{name:"Green 8"},
{name:"Green Draw 2"},
{name:"Green Skip"},
{name:"Green 2"},
{name:"Green Draw 2"},
{name:"Green 8"},
{name:"Green 9"},
{name:"Green Reverse"},
{name:"Green 9"},
{name:"Green 8"},
{name:"Green Draw 2"},
{name:"Green 7"},
{name:"Green Draw 2"},
{name:"Green 5"},
{name:"Green Draw 2"},
{name:"Green 7"},
{name:"Green Skip"},
{name:"Green 9"},
{name:"Green Reverse"},
{name:"Green Draw 2"},
{name:"Green Draw 2"},
{name:"Green Draw 2"},
{name:"Green Draw 2"},
{name:"Green Draw 2"},
{name:"Green Draw 2"}];
